# Generated by Django 6.0.5 on 2026-05-27 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_age_alter_pet_price_and_more'),
        ('users', '0002_alter_breedershelterprofile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breedershelterprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='breedershelterprofile',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='breedershelterprofile',
            name='profile_type',
        ),
        migrations.RemoveField(
            model_name='breedershelterprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='breedershelterprofile',
            name='is_shelter',
            field=models.BooleanField(default=False, help_text='Check if this is a shelter (animals are free). Uncheck for breeders.'),
        ),
        migrations.AlterField(
            model_name='breedershelterprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.city'),
        ),
    ]
